[project]
name = "football-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.32.3",
    "httpx>=0.27.0",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "scipy>=1.16.1",
]
